#Kabanero! on activate substitute StackId for text 'StackId'
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: StackId-build-push-pl
spec:
  workspaces:
  - name: varlibcontainers
  - name: mavenrepo
  params:
    - name: docker-imagename
      type: string
    - name: docker-imagetag
      type: string
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: enforce-stack-policy-task
      taskRef:
        name: StackId-validate-stack-task
      resources:
        inputs:
        - name: git-source
          resource: git-source
    - name: build-push-task
      taskRef:
        name: StackId-build-push-task
      runAfter: [enforce-stack-policy-task]
      workspaces:
        - name: varlibcontainers
          workspace: varlibcontainers
        - name: mavenrepo
          workspace: mavenrepo
      params:
        - name: docker-imagename
          value: "$(params.docker-imagename)"
        - name: docker-imagetag
          value: "$(params.docker-imagetag)"
      resources:
        inputs:
        - name: git-source
          resource: git-source
        - name: docker-image
          resource: docker-image
        outputs:
        - name: docker-image
          resource: docker-image
        - name: git-source
          resource: git-source
    - name: image-scan-task
      taskRef:
        name: StackId-image-scan-task
      runAfter: [build-push-task]
      params:
        - name: docker-imagename
          value: "$(params.docker-imagename)"
        - name: docker-imagetag
          value: "$(params.docker-imagetag)"
      resources:
        inputs:
        - name: git-source
          resource: git-source
        - name: docker-image
          resource: docker-image
