#Kabanero! on activate substitute Digest for text 'StackId'
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: StackId-deploy-task
spec:
  resources:
    inputs:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  params:
  - name: repository-name
    default: StackId
  - name: app-deploy-file-name
    default: app-deploy.yaml
  - name: docker-imagename
    type: string
    default: "null"
  - name: docker-imagetag
    type: string
    default: "null"
  steps:
  - name: enforce-stack-policy-pre-deploy
    securityContext:
      privileged: true
    image: kabanero/kabanero-utils@sha256:d2534cb30f618975bd5a9554920050b36d1bde5a882e8bacf100773847ec9ae8
    command: ["/bin/bash"]
    args:
      - -c
      - |
        INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE=$( /scripts/imageurl_imagename_lowercase.sh -u "$(inputs.resources.docker-image.url)" -n "$(inputs.params.docker-imagename)" -t "$(inputs.params.docker-imagetag)" )
        retVal=$?
        if [ $retVal -ne 0 ]; then
             echo "The script failed(/scripts/imageurl_imagename_lowercase.sh) Reason: $INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE" >&2
             exit $retVal
        fi
        echo "INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE=$INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE"
        /scripts/enforce_deploy_stack_policy.sh $INPUTS_RESOURCE_DOCKER_IMAGE_URL_LOWERCASE
        
    env:  
    - name: gitsource
      value: git-source
  - name: deploy-image
    image: kabanero/kabanero-utils@sha256:d2534cb30f618975bd5a9554920050b36d1bde5a882e8bacf100773847ec9ae8
    command: ['/bin/sh']
    args:
      - -c
      - |
         kubectl apply -f  /workspace/$gitsource/${YAMLFILE}
    env:
    - name: gitsource
      value: git-source
    - name: YAMLFILE
      value: $(inputs.params.app-deploy-file-name)
