#Kabanero! on activate substitute Digest for text 'StackId'
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: StackId-image-retag-pl
spec:
  resources:
    - name: docker-src-image
      type: image
    - name: docker-dest-image
      type: image
  tasks:
    - name: image-retag-task
      taskRef:
        name: StackId-image-retag-task
      resources:
        inputs:
        - name: docker-src-image
          resource: docker-src-image
        - name: docker-dest-image
          resource: docker-dest-image
        outputs:
        - name: docker-dest-image
          resource: docker-dest-image
