apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-src-image
  spec:
    params:
    - name: url
      value: index.docker.io/<docker_id>/<docker_image_name>:<source_tag_name>
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-dest-image
  spec:
    params:
    - name: url
      value: index.docker.io/<docker_id>/<docker_image_name>:<dest_tag_name>
    type: image
kind: List