apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: <stack-name>-manual-pipeline-run
spec:
  params:
  - name: event-type
    value: push
  - name: event-ref
    value: refs/heads/master
  - name: docker-imagename
    value: <stack-name>-image
  - name: docker-imagetag
    value: latest
  serviceAccountName: kabanero-pipeline
  timeout: "1h0m0s"
  pipelineRef:
    name: build-push-promote-pl-<stack-name>
  resources:
    - name: git-source
      resourceRef:
        name: git-source
    - name: docker-image
      resourceRef:
        name: docker-image