#Kabanero! on activate substitute StackId for text 'StackId'
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: StackId-validate-stack-task
spec:
  resources:
    inputs:
    - name: git-source
      type: git
  steps:
  - name: validate-stack-is-active
    securityContext:
      privileged: true
    image: kabanero/kabanero-utils@sha256:d2534cb30f618975bd5a9554920050b36d1bde5a882e8bacf100773847ec9ae8
    command: ["/bin/bash"]
    args:
      - -c
      - |
        #############
        # Functions #
        #############
        
        #################
        # ignoreDigests #
        #################
        ignore_digests () {
        
           # If the version was "latest", sort all the installed versions to find the latest
           if [ "$VERSION" == "latest" ] && [ ! -z CLUSTER_STACK_VERSIONS ]; then
              echo 
              echo "INFO: The application stack, "$PROJECT/$STACK_NAME:$VERSION", in $APPSODY_CONFIG is active on this cluster and passes stackPolicy validation."
              exit 0  
           fi
           for STACK_VERSION in ${CLUSTER_STACK_VERSIONS}; do            
              # If the stack version starts with same pattern, we are done
              if [[ "$STACK_VERSION" == $VERSION* ]]; then
                 echo 
                 echo "INFO: The application stack, "$PROJECT/$STACK_NAME:$VERSION", in $APPSODY_CONFIG is active on this cluster and passes stackPolicy validation."
                 exit 0  
              fi  
           done  
           echo "ERROR: A compatible version of the application stack, "$PROJECT/$STACK_NAME:$VERSION", is not active on this cluster. Please review the active versions of the stack on the cluster (oc get stack $STACK_NAME -o json) and the stack specification in the $APPSODY_CONFIG file of the git project."
           echo "ERROR: Stack fails stackPolicy validation." 
           exit 1
        }
        
        
        #################
        # activeDigests #
        #################
        active_digests () {
 
           # Find matching versions
           for STACK_VERSION in ${CLUSTER_STACK_VERSIONS}
              do
                 if [[ "$STACK_VERSION" == $VERSION* ]]; then
                    CANDIDATE_STACK_VERSIONS+=$STACK_VERSION" "
                 fi
              done
           # Sort matching versions
           SORTED_CLUSTER_STACK_VERSIONS=$( echo "$CANDIDATE_STACK_VERSIONS" | tr ' ' '\n' | sort | tr '\n' ' ' )
           if [ -z "$SORTED_CLUSTER_STACK_VERSIONS" ]; then
              echo
              echo "ERROR: $APPSODY_CONFIG specifies a stack version of $VERSION , but there are no matching versions active. Versions active: $CLUSTER_STACK_VERSIONS"
              exit 1
           else
              # PATCH APPSODY-CONFIG
              LATEST=$( echo $SORTED_CLUSTER_STACK_VERSIONS | awk '{print $NF}' )
              PATCHED=${STACK//$VERSION/$LATEST}
              sed -i -e "s|$STACK|$PATCHED|g" /workspace/$GITSOURCE/$APPSODY_CONFIG
              echo "WARN: .appsody-config.yaml, stack: value patched from '$STACK' to '$PATCHED' according to stackPolicy setting of 'activeDigest'"
              echo "INFO: The application stack, "$PROJECT/$STACK_NAME:$VERSION", in $APPSODY_CONFIG is active on this cluster and fails stackPolicy validation."
              exit 0
           fi
        }
        
        
        #################
        # strictDigests #
        #################
        strict_digests () {

           if [ "$STACK_POLICY" == "strictDigest" ]; then
              echo "ERROR: A compatible version of the application stack, "$PROJECT/$STACK_NAME:$VERSION", is not active on this cluster. Please review the active versions of the stack on the cluster (oc get stack $STACK_NAME -o json) and the stack specification in the $APPSODY_CONFIG file of the git project."
              exit 1
           else
              # TODO: Clarify message, copied
              echo "INFO: The application stack, "$PROJECT/$STACK_NAME:$VERSION", in $APPSODY_CONFIG is active on this cluster and passes stackPolicy validation."
              exit 0
           fi 
        }
       
        ###  MAIN ###
        
        
        # Configure image registry access in the container by adding it to the insecure registry list or enabling TLS verification
        # by adding it to the trust store based on OpenShift cluster resource configuration.
        echo "INFO: Running the script /scripts/image_registry_access_setup.sh ...."
        /scripts/image_registry_access_setup.sh
        retVal=$?
        if [ $retVal -ne 0 ]
        then
           echo "ERROR: The script failed(/scripts/image_registry_access_setup.sh), and the image registry access setup was not complete, aborting the pipelinerun." >&2
           exit $retVal
        fi
       
        # env var gitsource
        GITSOURCE=$gitsource
        APPSODY_CONFIG=".appsody-config.yaml"
        IMAGE_REGISTRY_HOST=$DEFAULT_STACK_IMAGE_REGISTRY_URL
        IMAGE_REGISTRY_USERNAME=$DEFAULT_STACK_IMAGE_REGISTRY_SECRET_USERNAME
        IMAGE_REGISTRY_PASSWORD=$DEFAULT_STACK_IMAGE_REGISTRY_SECRET_PASSWORD

        # Get stack policy
        # Values: strictDigest, activeDigest (default if blank), ignoreDigest and none
        # https://github.com/kabanero-io/kabanero-foundation/blob/master/design/digest.md

        STACK_POLICY=$( kubectl get kabanero kabanero -o json | jq -r '.spec.governancePolicy.stackPolicy' )
        # Default to value "activeDigest" - if the CR lacks a value, the default is to be used
        if [ -z "$STACK_POLICY" ] || [ "$STACK_POLICY" == "null" ]; then
           STACK_POLICY="activeDigest"
        fi
        
        if [ "$STACK_POLICY" == "none" ]; then
           echo
           echo "INFO: stackPolicy' under 'governancePolicy' is set to 'none', skipping stack validation."
           exit 0
        fi
        echo
        echo "INFO: Enforcing 'stackPolicy' of '$STACK_POLICY'."
        echo

        cd /workspace/$GITSOURCE
        if [ ! -f "$APPSODY_CONFIG" ]; then
           echo "ERROR: $APPSODY_CONFIG is not found in the root of the source directory. Unable to do stackPolicy validation."
           exit 1
        fi
        

        #########################################################################################
        # Read project, stack image, docker host and stack name from .appsody-config.yaml
        #########################################################################################
        echo
        echo "INFO: Read project, stack image, docker host and stack name from .appsody-config.yaml" 
        # Find the value for "stack:" from the appsody config file and assign it to the variable 'stack'
        declare $( awk '{if ($1 ~ "stack:"){printf "STACK="$2}}'  $APPSODY_CONFIG )
        if [ -z "$STACK" ]; then
           echo "INFO: $APPSODY_CONFIG does not contain a stack: definition. Unable to do stackPolicy validation."
           exit 1
        fi

        # Parse the image value for the repo, project, stackname and version
        # It can be in one of two formats based on appsody CLI used.
        # example 1: appsody/java-microprofile:0.2
        # example 2: image-registry.openshift-image-registry.svc:5000/kabanero/java-microprofile:0.2

        # For version get everything after last `:`
        VERSION="${STACK##*:}"
        echo "INFO: Git project config in $APPSODY_CONFIG... "
        echo "INFO: VERSION = $VERSION"

        # For project stack get everything before the last `:`
        PROJECT_STACK="${STACK%:*}"

        # The stack name could be after the 2nd or 3rd `/` based on appsody version. Check after 3rd first
        STACK_NAME="$(echo $PROJECT_STACK | cut -d'/' -f3 )"

        if [ -z "$STACK_NAME" ]; then
            PROJECT="$(echo $PROJECT_STACK | cut -d'/' -f1)"
            STACK_NAME="$( echo $PROJECT_STACK | cut -d'/' -f2 )"
        else
            STACK_REGISTRY="$(echo $PROJECT_STACK | cut -d'/' -f1)"
            PROJECT="$( echo $PROJECT_STACK | cut -d'/' -f2 )"
        fi

        echo "INFO: STACK_IMAGE_REGISTRY = $STACK_REGISTRY"
        echo "INFO: PROJECT = $PROJECT"
        echo "INFO: STACK_NAME = $STACK_NAME"

        # If the host wasn't specified, default to docker.io; if only specified in appsody-cfg.yaml use that
        # If it's in the config map use that and should match with what's in appsody-cfg.yaml
        if [ -z "$IMAGE_REGISTRY_HOST" ]; then
            if [ -z "$STACK_REGISTRY" ]; then
              IMAGE_REGISTRY_HOST="docker.io"
            else
              IMAGE_REGISTRY_HOST=$STACK_REGISTRY
            fi
        else
            if [ ! -z "$STACK_REGISTRY" ] && [ "$STACK_REGISTRY" != "$IMAGE_REGISTRY_HOST" ]; then
                RECONCILED_REGISTRY="TRUE"
                echo "WARNING: $APPSODY_CONFIG specifies different repository, $STACK_REGISTRY, than what's configured in the config map, $IMAGE_REGISTRY_HOST, in the cluster.  Config map entry takes priority.  Using $IMAGE_REGISTRY_HOST as the default stack registry."
            fi
        fi
        echo "INFO: Successfully read project, stack image, docker host and stack name from .appsody-config.yaml" 



        #########################################################################################
        # Validate stack name & project are present, active in the Kabanero CR
        #########################################################################################
        echo
        echo "INFO: Validate stack name & project are present, active in the Kabanero CR"
        # Check to make sure the stack is active by name first
        kubectl get stack $STACK_NAME -o json > /dev/null 2>&1
        if [ $? -ne 0 ]; then
           echo "ERROR: No versions of $STACK_NAME in $APPSODY_CONFIG are active in the cluster.  Stack fails stackPolicy validation since $STACK_NAME is not active."
           echo "ERROR: Stack messages = $?"
           exit 1
        fi
        # Check if the project names in the cfg file and active stack match
        CLUSTER_STACK_IMAGE=$( kubectl get stack $STACK_NAME  -o json | jq -r '.status.versions[].images[].image?' )
        echo "INFO: In the cluster..."
        echo "INFO: STACK_IMAGE = $CLUSTER_STACK_IMAGE"
        # The stack name could be after the 2nd or 3rd `/` based on appsody version. Check after 3rd first
        THIRD_ENTRY="$(echo $CLUSTER_STACK_IMAGE | cut -d'/' -f3 )"
        if [ -z "$THIRD_ENTRY" ]; then
            CLUSTER_PROJECT="$(echo $CLUSTER_STACK_IMAGE | cut -d'/' -f1)"
            CLUSTER_STACK="$(echo $CLUSTER_STACK_IMAGE | cut -d'/' -f2)"
        else
            CLUSTER_STACK_REGISTRY="$(echo $CLUSTER_STACK_IMAGE | cut -d'/' -f1)"
            CLUSTER_PROJECT="$( echo $CLUSTER_STACK_IMAGE | cut -d'/' -f2 )"
            CLUSTER_STACK="$(echo $CLUSTER_STACK_IMAGE | cut -d'/' -f3)"
        fi
        echo "INFO: STACK_IMAGE_REGISTRY = $CLUSTER_STACK_REGISTRY"
        echo "INFO: PROJECT = $CLUSTER_PROJECT"
        echo "INFO: STACK_NAME = $CLUSTER_STACK"
        if [ "$CLUSTER_PROJECT" != "$PROJECT" ]; then
            echo "ERROR: Project name, $CLUSTER_PROJECT, of active stack in cluster and project name in the stack in $APPSODY_CONFIG, $PROJECT, do not match."
            echo "ERROR: stackPolicy validation failed."
            exit 1
        fi
        echo "INFO: Sucessfully validated stack name & project are present, active in the Kabanero CR"

        #########################################################################################
        #  Main validation between operator and registry
        #########################################################################################
        # IgnoreDigests (always)  &  activeDigest (if failure for autopatch)
        CLUSTER_STACK_VERSIONS=$( kubectl get stack $STACK_NAME  -o json | jq -r '.status.versions[].version?' )
        CLUSTER_STACK_DIGESTS=$( kubectl get stack java-microprofile -o json | jq -r '.status.versions[].images[].digest.activation?' )
        echo
        echo "INFO: VERSIONS = $CLUSTER_STACK_VERSIONS"
        echo "INFO: DIGESTS  = $CLUSTER_STACK_DIGESTS"   
        
        if [ "$STACK_POLICY" == "ignoreDigest" ]; then
           ignore_digests
        fi

        # Get the target sha256 digest from the image registry. Use the proper credentials depending on what was passed to us
        echo "INFO: RECONCILED_STACK_IMAGE_REGISTRY_HOST = $IMAGE_REGISTRY_HOST"
        if [ -z "$IMAGE_REGISTRY_PASSWORD" ] || [ -z "$IMAGE_REGISTRY_USERNAME" ]; then
           TARGET_DIGEST=$( skopeo inspect docker://"$IMAGE_REGISTRY_HOST"/"$PROJECT"/"$STACK_NAME":"$VERSION" | jq '.Digest' )
        else
           TARGET_DIGEST=$( skopeo inspect --creds="$IMAGE_REGISTRY_USERNAME":"$IMAGE_REGISTRY_PASSWORD" docker://"$IMAGE_REGISTRY_HOST"/"$PROJECT"/"$STACK_NAME":"$VERSION" | jq '.Digest' )
        fi

        if [ -z "$TARGET_DIGEST" ]; then
           echo "$APPSODY_CONFIG specifies a stack version of $VERSION , but the image registry does not contain a version tagged with $VERSION, and fails stackPolicy validation."
           exit 1
        fi
 
        # Loop for digests - strictDigest & activeDigest
        for CURRENT_DIGEST in ${CLUSTER_STACK_DIGESTS}
           do              
              if [ "$TARGET_DIGEST" =  "\"sha256:$CURRENT_DIGEST\"" ]; then
                echo 
                echo "INFO: The application stack, "$PROJECT/$STACK_NAME:$VERSION", in $APPSODY_CONFIG is active on this cluster and passes stackPolicy validation."
                exit 0
              else
                 # Not found, iterate to next and pring debug info
                 echo "INFO: Cluster stack digest: $CURRENT_DIGEST"
                 echo "INFO: Project stack version: $VERSION, Project stack digest: $TARGET_DIGEST"
              fi
           done
        echo 
        
        
        if [ "$STACK_POLICY" == "strictDigest" ]; then
           strict_digests
        fi   
        
        if [ "$STACK_POLICY" == "activeDigest" ]; then
           active_digests
        fi   

        # All early exits, we should not get here
        echo "ERROR: stackPolicy of not $STACK_POLICY not recognized"
        exit 1
         
   
    env:
    - name: gitsource
      value: git-source
    - name: DEFAULT_STACK_IMAGE_REGISTRY_URL
      valueFrom:
        configMapKeyRef:
         name: stack-image-registry-map
         key: default-stack-image-registry-url
         optional: true
    - name: DEFAULT_STACK_IMAGE_REGISTRY_SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: default-stack-image-registry-secret
          key: username
          optional: true
    - name: DEFAULT_STACK_IMAGE_REGISTRY_SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: default-stack-image-registry-secret
          key: password
          optional: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - name: config-volume
      mountPath: /config
    - name: secret-volume
      mountPath: /etc/secret-volume
  volumes:
  - name: varlibcontainers
    emptyDir: {}
  - name: config-volume
    configMap:
      name: stack-image-registry-map
      optional: true
  - name: secret-volume
    secret:
      secretName: default-stack-image-registry-secret
      optional: true
